-- SQL to setup your Supabase database for Sri Basaveshwara
-- You can run this in the SQL Editor on your Supabase dashboard

-- 1. Create Fertilizers table
CREATE TABLE IF NOT EXISTS fertilizers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type TEXT DEFAULT 'General',
  unit TEXT DEFAULT 'KG',
  price DECIMAL(10, 2),
  description TEXT,
  stock INTEGER DEFAULT 0,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ensure required columns exist and handle constraints if table was created differently
DO $$ 
BEGIN 
  -- Stock
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'fertilizers' AND COLUMN_NAME = 'stock') THEN
    ALTER TABLE fertilizers ADD COLUMN stock INTEGER DEFAULT 0;
  END IF;
  
  -- Description
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'fertilizers' AND COLUMN_NAME = 'description') THEN
    ALTER TABLE fertilizers ADD COLUMN description TEXT;
  END IF;

  -- Category
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'fertilizers' AND COLUMN_NAME = 'category') THEN
    ALTER TABLE fertilizers ADD COLUMN category TEXT;
  END IF;

  -- Type (Handle the reported error)
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'fertilizers' AND COLUMN_NAME = 'type') THEN
    ALTER TABLE fertilizers ADD COLUMN type TEXT DEFAULT 'General';
  ELSE
    -- If it exists but might be NOT NULL without default, ensure it has a default
    ALTER TABLE fertilizers ALTER COLUMN type SET DEFAULT 'General';
  END IF;

  -- Unit
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'fertilizers' AND COLUMN_NAME = 'unit') THEN
    ALTER TABLE fertilizers ADD COLUMN unit TEXT DEFAULT 'KG';
  END IF;

  -- Handle ID type if it's currently BIGINT but needs to be UUID for some flows
  -- (Actually let's stick to UUID in the CREATE and check if we need migration)
  -- The error showed the user HAS UUID already.
END $$;

-- 2. Create Sales table
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number TEXT UNIQUE NOT NULL,
  customer_info JSONB,
  items JSONB,
  subtotal DECIMAL(10, 2),
  cgst DECIMAL(10, 2),
  sgst DECIMAL(10, 2),
  total DECIMAL(10, 2),
  billed_by TEXT,
  billed_by_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Profiles table (for custom user roles)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT,
  email TEXT UNIQUE,
  password_hash TEXT,
  role TEXT DEFAULT 'USER' CHECK (role IN ('USER', 'AGENT', 'ADMIN', 'SUPER_ADMIN')),
  status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'LOCKED', 'PENDING')),
  last_login TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ensure only ONE Super Admin can exist in the system
CREATE UNIQUE INDEX IF NOT EXISTS unique_super_admin ON profiles (role) WHERE role = 'SUPER_ADMIN';

-- Ensure password_hash exists if table was created earlier without it
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'profiles' AND COLUMN_NAME = 'password_hash') THEN
    ALTER TABLE profiles ADD COLUMN password_hash TEXT;
  END IF;
  
  -- Ensure ID has a default if it was missing
  ALTER TABLE profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();
END $$;

-- 4. Create Audit Logs table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  user_name TEXT,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create OTPs table for authentication
CREATE TABLE IF NOT EXISTS otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Populate initial fertilizers if the table is empty
INSERT INTO fertilizers (name, type, unit, price, description, stock, category)
SELECT 'Urea Fortified', 'Nitrogenous', 'KG', 450, 'High nitrogen content for green leaf growth.', 120, 'NITROGEN'
WHERE NOT EXISTS (SELECT 1 FROM fertilizers WHERE name = 'Urea Fortified');

INSERT INTO fertilizers (name, type, unit, price, description, stock, category)
SELECT 'DAP Premium', 'Phosphatic', 'KG', 1200, 'Phosphorus-rich fertilizer for root development.', 85, 'PHOSPHORUS'
WHERE NOT EXISTS (SELECT 1 FROM fertilizers WHERE name = 'DAP Premium');

INSERT INTO fertilizers (name, type, unit, price, description, stock, category)
SELECT 'NPK Compound', 'Complex', 'KG', 980, 'Balanced nutrients for overall plant health.', 200, 'BALANCED'
WHERE NOT EXISTS (SELECT 1 FROM fertilizers WHERE name = 'NPK Compound');

-- 4. Enable Row Level Security (optional but recommended)
-- Note: My Express backend uses the Service Role Key which bypasses RLS.
-- If you want to use the Anon Key directly from the frontend, you'll need RLS policies.
ALTER TABLE fertilizers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- Allow all for authenticated (this is a simple policy, harden as needed)
CREATE POLICY "Allow all to authenticated" ON fertilizers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all to authenticated" ON sales FOR ALL USING (auth.role() = 'authenticated');
